name: Setup Environment
inputs:
  SECRET_GITHUB_TOKEN:
    required: true
    description: 'Github Secret Token'
  CACHIX_TOKEN:
    required: true
    description: 'Cachix Secret Token'
runs:
  using: "composite"
  steps:

    - name: Installing Nix
      uses: cachix/install-nix-action@v21
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable
        github_access_token: ${{ inputs.SECRET_GITHUB_TOKEN }}

    - name: Configure Cachix
      uses: cachix/cachix-action@v12
      with:
        name: organist
        authToken: ${{ inputs.CACHIX_TOKEN }}
