name: Templates

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  setup:
    name: Setup nix and nickel-nix
    runs-on: ubuntu-latest

    outputs:
      

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup
      uses: ./.github/actions/common-setup
      with:
        SECRET_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: List all templates
      id: templates
      env:
      # Should only be needed until we use a `cachinx/install-nix` action that contains
      # https://github.com/cachix/install-nix-action/pull/152 (should be in `v19`)
      NIX_CONFIG: "extra-access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}"
    run: |
      kernels=$(nix eval .#packages.x86_64-linux --apply builtins.attrNames --json)
      echo $kernels
      filterKernels=$(echo $kernels | nix run nixpkgs#jq -- -c '[.[] | select(. | contains("jupyterlab-kernel-example-")) | ltrimstr("jupyterlab-kernel-")]')
      echo "kernels=$filterKernels" >> $GITHUB_OUTPUT
