name: Templates

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  enter-devshells:
    name: Test devshells
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup
      uses: ./.github/actions/common-setup
      with:
        SECRET_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CACHIX_TOKEN: ${{ secrets.CACHIX_TOKEN }}

    - name: Test devshells
      run: |
        nix develop --accept-flake-config --command bash run-test.sh template
        nix develop --accept-flake-config --command bash run-test.sh example examples/c-hello-world
